-- Catálogo inicial de "Lista de super"
-- Correr en el SQL Editor de Supabase DESPUÉS de haber corrido schema.sql
-- Carga todos los productos de una sola vez, sin marcar ninguno como necesitado.

insert into productos (nombre, categoria) values
-- Despensa
('Arroz', 'Despensa'),
('Fideos', 'Despensa'),
('Lentejas', 'Despensa'),
('Garbanzos', 'Despensa'),
('Porotos', 'Despensa'),
('Harina 0000', 'Despensa'),
('Harina leudante', 'Despensa'),
('Levadura', 'Despensa'),
('Polenta', 'Despensa'),
('Atún en lata', 'Despensa'),
('Tomate triturado', 'Despensa'),
('Choclo en lata', 'Despensa'),
('Arvejas en lata', 'Despensa'),
('Sal', 'Despensa'),
('Pimienta', 'Despensa'),
('Orégano', 'Despensa'),
('Comino', 'Despensa'),
('Pimentón', 'Despensa'),
('Ajo en polvo', 'Despensa'),
('Aceite de girasol', 'Despensa'),
('Aceite de oliva', 'Despensa'),
('Vinagre', 'Despensa'),
('Café', 'Despensa'),
('Té', 'Despensa'),
('Yerba', 'Despensa'),
('Azúcar', 'Despensa'),
('Edulcorante', 'Despensa'),
('Papas fritas', 'Despensa'),
('Galletitas dulces', 'Despensa'),
('Galletitas saladas', 'Despensa'),
('Chocolate', 'Despensa'),
('Mermelada', 'Despensa'),
('Mayonesa', 'Despensa'),
('Ketchup', 'Despensa'),
('Mostaza', 'Despensa'),
('Avena', 'Despensa'),
('Maicena', 'Despensa'),
('Caldo en cubos', 'Despensa'),
('Aceitunas', 'Despensa'),

-- Frutas y verduras
('Banana', 'Frutas y verduras'),
('Manzana', 'Frutas y verduras'),
('Naranja', 'Frutas y verduras'),
('Limón', 'Frutas y verduras'),
('Palta', 'Frutas y verduras'),
('Papa', 'Frutas y verduras'),
('Cebolla', 'Frutas y verduras'),
('Tomate', 'Frutas y verduras'),
('Zanahoria', 'Frutas y verduras'),
('Zapallo', 'Frutas y verduras'),
('Lechuga', 'Frutas y verduras'),
('Espinaca', 'Frutas y verduras'),
('Acelga', 'Frutas y verduras'),
('Ajo', 'Frutas y verduras'),
('Morrón', 'Frutas y verduras'),
('Brócoli', 'Frutas y verduras'),
('Repollo', 'Frutas y verduras'),
('Coliflor', 'Frutas y verduras'),
('Pepino', 'Frutas y verduras'),
('Batata', 'Frutas y verduras'),
('Apio', 'Frutas y verduras'),

-- Lácteos y huevos
('Leche', 'Lácteos y huevos'),
('Yogur', 'Lácteos y huevos'),
('Manteca', 'Lácteos y huevos'),
('Crema de leche', 'Lácteos y huevos'),
('Queso cremoso', 'Lácteos y huevos'),
('Queso rallado', 'Lácteos y huevos'),
('Queso duro', 'Lácteos y huevos'),
('Huevos', 'Lácteos y huevos'),
('Queso untable', 'Lácteos y huevos'),
('Leche chocolatada', 'Lácteos y huevos'),

-- Carnes y fiambres
('Carne picada', 'Carnes y fiambres'),
('Carne vacuna', 'Carnes y fiambres'),
('Pollo', 'Carnes y fiambres'),
('Milanesas', 'Carnes y fiambres'),
('Pescado', 'Carnes y fiambres'),
('Jamón cocido', 'Carnes y fiambres'),
('Jamón crudo', 'Carnes y fiambres'),
('Salame', 'Carnes y fiambres'),
('Mortadela', 'Carnes y fiambres'),
('Salchichas', 'Carnes y fiambres'),
('Hamburguesas', 'Carnes y fiambres'),

-- Limpieza
('Detergente multiuso', 'Limpieza'),
('Lavandina', 'Limpieza'),
('Limpiavidrios', 'Limpieza'),
('Desinfectante de pisos', 'Limpieza'),
('Jabón en polvo', 'Limpieza'),
('Suavizante para ropa', 'Limpieza'),
('Quitamanchas', 'Limpieza'),
('Detergente para platos', 'Limpieza'),
('Esponjas de cocina', 'Limpieza'),
('Trapo de piso', 'Limpieza'),
('Trapo rejilla', 'Limpieza'),
('Repasadores', 'Limpieza'),
('Escoba', 'Limpieza'),
('Pala de basura', 'Limpieza'),
('Balde', 'Limpieza'),
('Lustramuebles', 'Limpieza'),
('Ambientador', 'Limpieza'),
('Guantes de goma', 'Limpieza'),

-- Baño e higiene personal
('Pasta dental', 'Baño e higiene personal'),
('Cepillo de dientes', 'Baño e higiene personal'),
('Hilo dental', 'Baño e higiene personal'),
('Enjuague bucal', 'Baño e higiene personal'),
('Jabón de tocador', 'Baño e higiene personal'),
('Shampoo', 'Baño e higiene personal'),
('Acondicionador', 'Baño e higiene personal'),
('Desodorante', 'Baño e higiene personal'),
('Papel higiénico', 'Baño e higiene personal'),
('Servilletas', 'Baño e higiene personal'),
('Papel de cocina', 'Baño e higiene personal'),
('Toallitas/tampones', 'Baño e higiene personal'),
('Algodón', 'Baño e higiene personal'),
('Hisopos', 'Baño e higiene personal'),
('Máquina de afeitar', 'Baño e higiene personal'),
('Crema de afeitar', 'Baño e higiene personal'),
('Crema corporal', 'Baño e higiene personal'),
('Protector solar', 'Baño e higiene personal'),
('Preservativos', 'Baño e higiene personal'),
('Repelente de mosquitos', 'Baño e higiene personal'),
('Protector labial', 'Baño e higiene personal'),

-- Cocina (descartables)
('Film de cocina', 'Cocina (descartables)'),
('Papel aluminio', 'Cocina (descartables)'),
('Bolsas de residuo', 'Cocina (descartables)'),
('Bolsas para freezer', 'Cocina (descartables)'),
('Guantes descartables', 'Cocina (descartables)'),
('Vasos descartables', 'Cocina (descartables)'),
('Platos descartables', 'Cocina (descartables)'),

-- Farmacia / botiquín
('Paracetamol', 'Farmacia / botiquín'),
('Ibuprofeno', 'Farmacia / botiquín'),
('Antiácido', 'Farmacia / botiquín'),
('Gasas', 'Farmacia / botiquín'),
('Alcohol', 'Farmacia / botiquín'),
('Alcohol en gel', 'Farmacia / botiquín'),
('Curitas', 'Farmacia / botiquín'),
('Vendas', 'Farmacia / botiquín'),
('Antihistamínico', 'Farmacia / botiquín'),
('Termómetro', 'Farmacia / botiquín'),

-- Otros / hogar
('Pilas AA', 'Otros / hogar'),
('Pilas AAA', 'Otros / hogar'),
('Velas', 'Otros / hogar'),
('Bombitas de luz LED', 'Otros / hogar'),
('Fósforos', 'Otros / hogar'),
('Encendedor', 'Otros / hogar'),
('Bolsas para aspiradora', 'Otros / hogar'),
('Cinta adhesiva', 'Otros / hogar');
